
package com.helloworld.ws;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "WSS", targetNamespace = "com.org.helloworld")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface WSS {


    /**
     * 
     * @param student
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "addStudent", targetNamespace = "com.org.helloworld", className = "com.helloworld.ws.AddStudent")
    @ResponseWrapper(localName = "addStudentResponse", targetNamespace = "com.org.helloworld", className = "com.helloworld.ws.AddStudentResponse")
    public boolean addStudent(
        @WebParam(name = "student", targetNamespace = "")
        StudentDTO student);

    /**
     * 
     */
    @WebMethod
    @RequestWrapper(localName = "populate", targetNamespace = "com.org.helloworld", className = "com.helloworld.ws.Populate")
    @ResponseWrapper(localName = "populateResponse", targetNamespace = "com.org.helloworld", className = "com.helloworld.ws.PopulateResponse")
    public void populate();

    /**
     * 
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "sayHello", targetNamespace = "com.org.helloworld", className = "com.helloworld.ws.SayHello")
    @ResponseWrapper(localName = "sayHelloResponse", targetNamespace = "com.org.helloworld", className = "com.helloworld.ws.SayHelloResponse")
    public String sayHello();

    /**
     * 
     * @return
     *     returns java.util.List<com.helloworld.ws.StudentDTO>
     */
    @WebMethod
    @WebResult(name = "studentList", targetNamespace = "")
    @RequestWrapper(localName = "getStudentList", targetNamespace = "com.org.helloworld", className = "com.helloworld.ws.GetStudentList")
    @ResponseWrapper(localName = "getStudentListResponse", targetNamespace = "com.org.helloworld", className = "com.helloworld.ws.GetStudentListResponse")
    public List<StudentDTO> getStudentList();

    /**
     * 
     * @param id
     * @return
     *     returns com.helloworld.ws.StudentDTO
     */
    @WebMethod
    @WebResult(name = "student", targetNamespace = "")
    @RequestWrapper(localName = "getStudent", targetNamespace = "com.org.helloworld", className = "com.helloworld.ws.GetStudent")
    @ResponseWrapper(localName = "getStudentResponse", targetNamespace = "com.org.helloworld", className = "com.helloworld.ws.GetStudentResponse")
    public StudentDTO getStudent(
        @WebParam(name = "id", targetNamespace = "")
        int id);

}
